### ISSUE TITLE
missing published extension

### ISSUE THREAD

**Issue by daiyam** [HaaLeo/publish-vscode-extension#29] opened 2022-11-12 20:46 UTC
| publish-vscode-extension Version | Operating System |
| -------------------------------------- | ---------------- |
|             v1.1.0                           |      Ubuntu  20.04.5  LTS            |

# Description

Hi Leo,

I can't publish my extension to OpenVSX.
I'm not sure if it's an issue with your extension or OpenVSX.

The publishing was successful but the extension is missing on OpenVSX.

```
##[debug]Evaluating condition for step: 'Publish to Open VSX Registry'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Publish to Open VSX Registry
##[debug]Loading inputs
##[debug]Evaluating: secrets.OPEN_VSX_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'OPEN_VSX_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run HaaLeo/publish-vscode-extension@v1
Specifically, running GitHub Action HaaLeo/publish-vscode-extension@v1.1.0.
##[debug]Start action with options="{"pat":"***","registryUrl":"https://open-vsx.org","packagePath":"./","yarn":false,"dryRun":false,"noVerify":false,"preRelease":false}".
::group::Package the Extension
Package the Extension
::group::Publish the Extension
Publish the Extension
  ::endgroup::
##[debug]Node Action run completed with exit code 0
##[debug]Set output vsixPath = explicit-folding-0.23.0.vsix
##[debug]Finishing: Publish to Open VSX Registry
```

Is it possible to output the logs of the command?

**Comment by daiyam** [comment] 2022-11-13 00:01
I was able to publish the extension and I did get the log:
>   🚀  Published zokugun.explicit-folding v0.23.1

I just wonder why the action didn't fail if there were a error somewhere...

**Comment by HaaLeo** [comment] 2022-11-14 21:12
Hi @daiyam thx for reporting this bug. The action should definitely fail when errors occur.

Without being able to reproduce the behavior consistently this will be hard to debug. Can you reproduce this one or it just went away the next try?

**Comment by daiyam** [comment] 2022-11-14 21:38
I tried to publish my [extension](https://open-vsx.org/extension/zokugun/explicit-folding) `v0.23.0` 3 times:
 - 1: I stopped the workflow since it was running for already 6 minutes
 - 2: 5 minutes later, I re-run the workflow, the action takes 100s but there is no output and is marked successful.
 - 3: 12 minutes later, I re-run the workflow, the action takes 0s still no output and still successful.
 - 4: 3h30 later, I have a new minor version, it publish without any issue...
 
So I can't reproduce the error. Sorry. But I don't think the issue is due to your extension.
You might just want to capture the output and verify if it match the expect output...

**Comment by jeronimoek** [comment] 2023-02-17 05:27
The same happens to me, the ovsx CLI output is a success message, but no new version is published, so I guess the issue lies in their CLI

**Comment by jeronimoek** [comment] 2023-02-17 05:34
My output:
```
Run HaaLeo/publish-vscode-extension@v1
  with:
    pat: ***
    extensionFile: color-picker-universal.vsix
    registryUrl: https://open-vsx.org
    packagePath: ./
    yarn: false
    dryRun: false
    noVerify: false
    preRelease: false
Specifically, running GitHub Action HaaLeo/publish-vscode-extension@v1.[2](https://github.com/jeronimoek/color-picker-universal/actions/runs/4200887871/jobs/7287390587#step:9:2).0.
Package the Extension
  The extension was already packaged. Skip packaging.
Publish the Extension
  🚀  Published JeronimoEkerdt.color-picker-universal v1.[7](https://github.com/jeronimoek/color-picker-universal/actions/runs/4200887871/jobs/7287390587#step:9:7).1
```

**Comment by jeronimoek** [comment] 2023-02-17 05:54
Never mind, I just checked again, and after 1 hour approx. the extension was suddenly published. Looks like ovsx servers are struggling

**Comment by HaaLeo** [comment] 2023-04-01 09:23
As it seems to be an upstream issue I will mark it as "wontfix". If you find any hints which suggest this is a problem of this action feel free to reopen this issue.

**Closed by HaaLeo** 2023-04-01 09:23 UTC
Labels: bug
