### ISSUE TITLE
support pass args to vsce

### ISSUE THREAD

**Issue by tjx666** [HaaLeo/publish-vscode-extension#36] opened 2023-02-25 11:16 UTC
I need set `--no-dependencies` when publish extension with pnpm

details here: https://github.com/microsoft/vscode-vsce/issues/421#issuecomment-1038911725

failed github action: https://github.com/tjx666/awesome-vscode-extension-boilerplate/actions/runs/4269744506/jobs/7433113168

**Comment by HaaLeo** [comment] 2023-04-01 09:06
duplicate of #34

**Closed by HaaLeo** 2023-04-01 09:06 UTC
Labels: duplicate
